library(boot)
require(boot)
cd4
?cd4
plot(cd4$baseline)
stem(cd4$baseline)
library(aplpack)
# install.packages(("aplpack"))
stem.leaf.backback(cd4$baseline, cd4$oneyear)
boxplot(cd4$baseline, horizontal = TRUE)
hist(cd4$baseline)
plot(cd4)
cor(cd4)
n = length(cd4$baseline)
join = c(cd4$baseline, cd4$oneyear)
group = rep(c(0,1), each=n)
par(mfrow=c(1,3))
plot(group, join, axes=FALSE)
plot(jitter(group),join, axes=FALSE)
plot(group, join, axes=FALSE)
for (i in 1:n) 
lines(c(0,1),c(cd4$baseline[i], cd4$oneyear[i]))

library('graphics')
attach(cd4)
oneyear
plot(cd4)
dev.off()
plot(cd4, axes=FALSE, col='red')
rug(baseline, side =1)
rug(oneyear, side =2)
rug(baseline, side =3)
library(MVA)
install.packages("MVA")
install.packages("HSAUR2")
install.packages("tools")
bvbox(cd4)
